---
title: "Pesquisa Reproduzível com R"
output:
  html_document:
    toc: false
---

```{r setup, include=FALSE}
source("setup_knitr.R")
```

# Apresentação

**Pesquisa reproduzível com o R: de documentos dinâmicos a pacotes** é
um minicurso que será apresentado na [RBRAS 2016][], em Salvador (BA),
nos dias 24 e 25 de maio de 2016.

Os instrutores são [Fernando Mayer][] e [Walmes Zeviani][] (LEG/UFPR).

# Resumo

Pesquisa reproduzível é a ideia geral onde análise de dados, e de
maneira mais geral, descobertas científicas, devem ser publicadas
contendo os dados e o código de análise, para que outras pessoas possam
verificar os resultados e até mesmo continuar a construir ideias sobre
eles. A necessidade da reproducibilidade vem crescendo drasticamente, ao
mesmo tempo que as análises de dados estão se tornando mais complexas,
envolvendo grandes bases de dados e alto processamento computacional. A
reproducibilidade torna um resultado de uma pesquisa mais útil para
qualquer pessoa, pois os dados e o código que realmente geraram os
resultados estão disponíveis.

Este curso será focado nas ferramentas para análise estatística
documentada, que permitem que cientistas publiquem suas análises em um
único documento que irá permitir que outros cientistas executem a mesma
análise e obtenham os mesmos resultados. O objetivo é fornecer os
conceitos e ferramentas por trás da comunicação de análises de dados
modernas, de maneira reproduzível.

A importância de reproducibilidade na ciência é altamente reconhecida
hoje em dia, mas ainda não é largamente praticada como deveria ser. Um
dos motivos é que muitos cientistas não adotaram ainda as ferramentas
necessárias para a pesquisa reproduzível. Neste curso serão discutidos
os princípios gerais para a pesquisa reproduzível, mas o foco será
prioritariamente no uso das ferramentas relevantes.

Particularmente, será demonstrado como gerar relatórios dinâmicos com o
R, e de maneira mais aprofundada, como criar pacotes do R contendo
dados, análises e funções, com a intenção de facilitar a distribuição de
comunicações científicas. Para isso, serão utilizados alguns pacotes
modernos e auxiliares do R, como `knitr`, `rmarkdown`, `devtools`, e
`roxygen2`.

A intenção é que os atendentes do curso saiam preparados para utilizar
essas ferramentas em suas próprias pesquisas, ajudando a ampliar a forma
como se faz pesquisa reproduzível atualmente.

[RBRAS 2016]: http://rbras2016.ufba.br/pt/
[Fernando Mayer]: http://www.leg.ufpr.br/~fernandomayer
[Walmes Zeviani]: http://www.leg.ufpr.br/~walmes
